# coding: utf-8

"""
    API's OpenData do Open Banking Brasil

    As API's descritas neste documento são referentes as API's da fase OpenData do Open Banking Brasil.  # noqa: E501

    OpenAPI spec version: 1.0.0-rc5.2
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ApplicationRate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'interval': 'ApplicationIntervals',
        'indexer': 'Indexer',
        'customers': 'Customer'
    }

    attribute_map = {
        'interval': 'interval',
        'indexer': 'indexer',
        'customers': 'customers'
    }

    def __init__(self, interval=None, indexer=None, customers=None):  # noqa: E501
        """ApplicationRate - a model defined in Swagger"""  # noqa: E501
        self._interval = None
        self._indexer = None
        self._customers = None
        self.discriminator = None
        self.interval = interval
        self.indexer = indexer
        self.customers = customers

    @property
    def interval(self):
        """Gets the interval of this ApplicationRate.  # noqa: E501


        :return: The interval of this ApplicationRate.  # noqa: E501
        :rtype: ApplicationIntervals
        """
        return self._interval

    @interval.setter
    def interval(self, interval):
        """Sets the interval of this ApplicationRate.


        :param interval: The interval of this ApplicationRate.  # noqa: E501
        :type: ApplicationIntervals
        """
        if interval is None:
            raise ValueError("Invalid value for `interval`, must not be `None`")  # noqa: E501

        self._interval = interval

    @property
    def indexer(self):
        """Gets the indexer of this ApplicationRate.  # noqa: E501


        :return: The indexer of this ApplicationRate.  # noqa: E501
        :rtype: Indexer
        """
        return self._indexer

    @indexer.setter
    def indexer(self, indexer):
        """Sets the indexer of this ApplicationRate.


        :param indexer: The indexer of this ApplicationRate.  # noqa: E501
        :type: Indexer
        """
        if indexer is None:
            raise ValueError("Invalid value for `indexer`, must not be `None`")  # noqa: E501

        self._indexer = indexer

    @property
    def customers(self):
        """Gets the customers of this ApplicationRate.  # noqa: E501


        :return: The customers of this ApplicationRate.  # noqa: E501
        :rtype: Customer
        """
        return self._customers

    @customers.setter
    def customers(self, customers):
        """Sets the customers of this ApplicationRate.


        :param customers: The customers of this ApplicationRate.  # noqa: E501
        :type: Customer
        """
        if customers is None:
            raise ValueError("Invalid value for `customers`, must not be `None`")  # noqa: E501

        self._customers = customers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApplicationRate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApplicationRate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
