# coding: utf-8

"""
    API's OpenData do Open Banking Brasil

    As API's descritas neste documento são referentes as API's da fase OpenData do Open Banking Brasil.  # noqa: E501

    OpenAPI spec version: 1.0.0-rc5.2
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ServiceBundle(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'services': 'list[ServiceBundleServiceDetail]',
        'prices': 'list[MonthlyPrice]',
        'minimum': 'MinimumPrice',
        'maximum': 'MaximumPrice'
    }

    attribute_map = {
        'name': 'name',
        'services': 'services',
        'prices': 'prices',
        'minimum': 'minimum',
        'maximum': 'maximum'
    }

    def __init__(self, name=None, services=None, prices=None, minimum=None, maximum=None):  # noqa: E501
        """ServiceBundle - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._services = None
        self._prices = None
        self._minimum = None
        self._maximum = None
        self.discriminator = None
        self.name = name
        self.services = services
        self.prices = prices
        self.minimum = minimum
        self.maximum = maximum

    @property
    def name(self):
        """Gets the name of this ServiceBundle.  # noqa: E501

        Nome do Pacote de Serviços dado pela instituição.  # noqa: E501

        :return: The name of this ServiceBundle.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ServiceBundle.

        Nome do Pacote de Serviços dado pela instituição.  # noqa: E501

        :param name: The name of this ServiceBundle.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def services(self):
        """Gets the services of this ServiceBundle.  # noqa: E501

        Lista dos serviços que compõe o pacote de serviços  # noqa: E501

        :return: The services of this ServiceBundle.  # noqa: E501
        :rtype: list[ServiceBundleServiceDetail]
        """
        return self._services

    @services.setter
    def services(self, services):
        """Sets the services of this ServiceBundle.

        Lista dos serviços que compõe o pacote de serviços  # noqa: E501

        :param services: The services of this ServiceBundle.  # noqa: E501
        :type: list[ServiceBundleServiceDetail]
        """
        if services is None:
            raise ValueError("Invalid value for `services`, must not be `None`")  # noqa: E501

        self._services = services

    @property
    def prices(self):
        """Gets the prices of this ServiceBundle.  # noqa: E501

        Lista distribuição preços tarifas de serviços  # noqa: E501

        :return: The prices of this ServiceBundle.  # noqa: E501
        :rtype: list[MonthlyPrice]
        """
        return self._prices

    @prices.setter
    def prices(self, prices):
        """Sets the prices of this ServiceBundle.

        Lista distribuição preços tarifas de serviços  # noqa: E501

        :param prices: The prices of this ServiceBundle.  # noqa: E501
        :type: list[MonthlyPrice]
        """
        if prices is None:
            raise ValueError("Invalid value for `prices`, must not be `None`")  # noqa: E501

        self._prices = prices

    @property
    def minimum(self):
        """Gets the minimum of this ServiceBundle.  # noqa: E501


        :return: The minimum of this ServiceBundle.  # noqa: E501
        :rtype: MinimumPrice
        """
        return self._minimum

    @minimum.setter
    def minimum(self, minimum):
        """Sets the minimum of this ServiceBundle.


        :param minimum: The minimum of this ServiceBundle.  # noqa: E501
        :type: MinimumPrice
        """
        if minimum is None:
            raise ValueError("Invalid value for `minimum`, must not be `None`")  # noqa: E501

        self._minimum = minimum

    @property
    def maximum(self):
        """Gets the maximum of this ServiceBundle.  # noqa: E501


        :return: The maximum of this ServiceBundle.  # noqa: E501
        :rtype: MaximumPrice
        """
        return self._maximum

    @maximum.setter
    def maximum(self, maximum):
        """Sets the maximum of this ServiceBundle.


        :param maximum: The maximum of this ServiceBundle.  # noqa: E501
        :type: MaximumPrice
        """
        if maximum is None:
            raise ValueError("Invalid value for `maximum`, must not be `None`")  # noqa: E501

        self._maximum = maximum

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ServiceBundle, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServiceBundle):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
