# coding: utf-8

# flake8: noqa
"""
    APIs OpenData do Open Banking Brasil

    As APIs descritas neste documento são referentes as APIs da fase OpenData do Open Banking Brasil.  # noqa: E501

    OpenAPI spec version: 1.0.0-rc5.2
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from common_client.models.links import Links
from common_client.models.meta import Meta
from common_client.models.response_discovery_outage_list import ResponseDiscoveryOutageList
from common_client.models.response_discovery_outage_list_data import ResponseDiscoveryOutageListData
from common_client.models.response_discovery_status_list import ResponseDiscoveryStatusList
from common_client.models.response_discovery_status_list_data import ResponseDiscoveryStatusListData
from common_client.models.status import Status
