# coding: utf-8

"""
    APIs OpenData do Open Banking Brasil

    As APIs descritas neste documento são referentes as APIs da fase OpenData do Open Banking Brasil.  # noqa: E501

    OpenAPI spec version: 1.0.0-rc5.2
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from channels_client.models.cnpj import CNPJ  # noqa: F401,E501

class PhoneChannelsCompany(CNPJ):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'url_complementary_list': 'str',
        'phone_channels': 'list[PhoneChannel]'
    }
    if hasattr(CNPJ, "swagger_types"):
        swagger_types.update(CNPJ.swagger_types)

    attribute_map = {
        'name': 'name',
        'url_complementary_list': 'urlComplementaryList',
        'phone_channels': 'phoneChannels'
    }
    if hasattr(CNPJ, "attribute_map"):
        attribute_map.update(CNPJ.attribute_map)

    def __init__(self, name=None, url_complementary_list=None, phone_channels=None, *args, **kwargs):  # noqa: E501
        """PhoneChannelsCompany - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._url_complementary_list = None
        self._phone_channels = None
        self.discriminator = None
        self.name = name
        if url_complementary_list is not None:
            self.url_complementary_list = url_complementary_list
        self.phone_channels = phone_channels
        CNPJ.__init__(self, *args, **kwargs)

    @property
    def name(self):
        """Gets the name of this PhoneChannelsCompany.  # noqa: E501

        Nome da Instituição, pertencente à organização, responsável pelo Canal Telefônico.  # noqa: E501

        :return: The name of this PhoneChannelsCompany.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PhoneChannelsCompany.

        Nome da Instituição, pertencente à organização, responsável pelo Canal Telefônico.  # noqa: E501

        :param name: The name of this PhoneChannelsCompany.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def url_complementary_list(self):
        """Gets the url_complementary_list of this PhoneChannelsCompany.  # noqa: E501


        :return: The url_complementary_list of this PhoneChannelsCompany.  # noqa: E501
        :rtype: str
        """
        return self._url_complementary_list

    @url_complementary_list.setter
    def url_complementary_list(self, url_complementary_list):
        """Sets the url_complementary_list of this PhoneChannelsCompany.


        :param url_complementary_list: The url_complementary_list of this PhoneChannelsCompany.  # noqa: E501
        :type: str
        """

        self._url_complementary_list = url_complementary_list

    @property
    def phone_channels(self):
        """Gets the phone_channels of this PhoneChannelsCompany.  # noqa: E501

        Lista  de canais de atendimento telefônico  # noqa: E501

        :return: The phone_channels of this PhoneChannelsCompany.  # noqa: E501
        :rtype: list[PhoneChannel]
        """
        return self._phone_channels

    @phone_channels.setter
    def phone_channels(self, phone_channels):
        """Sets the phone_channels of this PhoneChannelsCompany.

        Lista  de canais de atendimento telefônico  # noqa: E501

        :param phone_channels: The phone_channels of this PhoneChannelsCompany.  # noqa: E501
        :type: list[PhoneChannel]
        """
        if phone_channels is None:
            raise ValueError("Invalid value for `phone_channels`, must not be `None`")  # noqa: E501

        self._phone_channels = phone_channels

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PhoneChannelsCompany, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PhoneChannelsCompany):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
