# coding: utf-8

"""
    APIs Admin do Open Banking Brasil

    As API's administrativas são recursos que podem ser consumidos apenas pelo diretório para avaliação e controle da qualidade dos serviços fornecidos pelas instituições financeiras  # noqa: E501

    OpenAPI spec version: 1.0.0-rc5.2
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AvailabilityMetricsUptime(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'general_uptime_rate': 'str',
        'endpoints': 'EndpointUptime'
    }

    attribute_map = {
        'general_uptime_rate': 'generalUptimeRate',
        'endpoints': 'endpoints'
    }

    def __init__(self, general_uptime_rate=None, endpoints=None):  # noqa: E501
        """AvailabilityMetricsUptime - a model defined in Swagger"""  # noqa: E501
        self._general_uptime_rate = None
        self._endpoints = None
        self.discriminator = None
        self.general_uptime_rate = general_uptime_rate
        self.endpoints = endpoints

    @property
    def general_uptime_rate(self):
        """Gets the general_uptime_rate of this AvailabilityMetricsUptime.  # noqa: E501

        Taxa de disponibilidade (considerando todos os serviços ativos ao mesmo tempo).  # noqa: E501

        :return: The general_uptime_rate of this AvailabilityMetricsUptime.  # noqa: E501
        :rtype: str
        """
        return self._general_uptime_rate

    @general_uptime_rate.setter
    def general_uptime_rate(self, general_uptime_rate):
        """Sets the general_uptime_rate of this AvailabilityMetricsUptime.

        Taxa de disponibilidade (considerando todos os serviços ativos ao mesmo tempo).  # noqa: E501

        :param general_uptime_rate: The general_uptime_rate of this AvailabilityMetricsUptime.  # noqa: E501
        :type: str
        """
        if general_uptime_rate is None:
            raise ValueError("Invalid value for `general_uptime_rate`, must not be `None`")  # noqa: E501

        self._general_uptime_rate = general_uptime_rate

    @property
    def endpoints(self):
        """Gets the endpoints of this AvailabilityMetricsUptime.  # noqa: E501


        :return: The endpoints of this AvailabilityMetricsUptime.  # noqa: E501
        :rtype: EndpointUptime
        """
        return self._endpoints

    @endpoints.setter
    def endpoints(self, endpoints):
        """Sets the endpoints of this AvailabilityMetricsUptime.


        :param endpoints: The endpoints of this AvailabilityMetricsUptime.  # noqa: E501
        :type: EndpointUptime
        """
        if endpoints is None:
            raise ValueError("Invalid value for `endpoints`, must not be `None`")  # noqa: E501

        self._endpoints = endpoints

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AvailabilityMetricsUptime, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AvailabilityMetricsUptime):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
