# coding: utf-8

"""
    APIs Admin do Open Banking Brasil

    As API's administrativas são recursos que podem ser consumidos apenas pelo diretório para avaliação e controle da qualidade dos serviços fornecidos pelas instituições financeiras  # noqa: E501

    OpenAPI spec version: 1.0.0-rc5.2
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EndpointUptime(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'url': 'str',
        'uptime_rate': 'str'
    }

    attribute_map = {
        'url': 'url',
        'uptime_rate': 'uptimeRate'
    }

    def __init__(self, url=None, uptime_rate=None):  # noqa: E501
        """EndpointUptime - a model defined in Swagger"""  # noqa: E501
        self._url = None
        self._uptime_rate = None
        self.discriminator = None
        self.url = url
        self.uptime_rate = uptime_rate

    @property
    def url(self):
        """Gets the url of this EndpointUptime.  # noqa: E501

        URL do endpoint  # noqa: E501

        :return: The url of this EndpointUptime.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this EndpointUptime.

        URL do endpoint  # noqa: E501

        :param url: The url of this EndpointUptime.  # noqa: E501
        :type: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    @property
    def uptime_rate(self):
        """Gets the uptime_rate of this EndpointUptime.  # noqa: E501

        Taxa de disponibilidade do endpoint.  # noqa: E501

        :return: The uptime_rate of this EndpointUptime.  # noqa: E501
        :rtype: str
        """
        return self._uptime_rate

    @uptime_rate.setter
    def uptime_rate(self, uptime_rate):
        """Sets the uptime_rate of this EndpointUptime.

        Taxa de disponibilidade do endpoint.  # noqa: E501

        :param uptime_rate: The uptime_rate of this EndpointUptime.  # noqa: E501
        :type: str
        """
        if uptime_rate is None:
            raise ValueError("Invalid value for `uptime_rate`, must not be `None`")  # noqa: E501

        self._uptime_rate = uptime_rate

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EndpointUptime, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EndpointUptime):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
